name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: 'New'
    labels:
      - 'enhancement'
  - title: 'Fixes'
    labels:
      - 'bug'
template: |
  ## Changes
  $CHANGES
